### ISSUE TITLE
On model save, using backbone_rails_sync and {patch: true}, the entire model's attributes are sent to Rails.

### ISSUE THREAD

**Issue by reidcooper** [codebrew/backbone-rails#198] opened 2016-05-20 18:36 UTC
https://github.com/codebrew/backbone-rails/blob/master/vendor/assets/javascripts/backbone_rails_sync.js

When passing `{patch: true}` to a model save, typically Backbone should be sending only the changed attributes to the server. Now when using the `backbone_rails_sync.js` override, using `{patch: true}` does not send the changed attributes but sends the entire model to rails. I am guessing during the override, backbone may think that the entire model attributes have been changed, therefore sending those values? When I do not use `backbone_rails_sync.js`, Backbone sends the proper changed attributes.

**Comment by jmadureira** [comment] 2016-06-01 14:45
Actually looking at the code it's treating create, update and patch the exact same way.
I suppose that for patch it should be calling changedAttributes instead of calling toJSON for the entire model.

**Comment by jmadureira** [comment] 2016-06-01 15:30
I was able to get this running with the following code:

``` javascript
if ((options.data == null) && model && (method === 'create' || method === 'update' || method === 'patch')) {
  options.contentType = 'application/json';
  data = {};
  if (model.paramRoot) {
    data = {};
    data[model.paramRoot] = options.attrs || model.toJSON(options);
  } else {
    data = options.attrs || model.toJSON(options);
  }
  options.data = JSON.stringify(data);
}
```

Haven't had the time to test it more thoroughly but so far all test from my app are passing...

**Comment by jmadureira** [comment] 2016-06-02 21:19
Turns out this is a duplicate of #188.

**Closed as completed** 2020-03-09 16:35 UTC
